# Basic information
site_name: "HR-бренд и все вытекающие"
site_description: "Развитие HR-бренда компании: стратегии, кейсы, лучшие практики. Глубокий анализ внутреннего и внешнего HR-брендинга"
site_author: "Бойко Екатерина"
site_url: "https://github.com/pustaaten/devops-lab-boiko"

# Repository
repo_name: pustaaten/devops-lab-boiko
repo_url: https://github.com/pustaaten/devops-lab-boiko

# Copyright
copyright: "Copyright &copy; 2020 - 2025 Бойко Екатерина"

# Theme configuration
theme:
  name: material
  logo: images/logo.jpg
  language: ru
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
  

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/kaboyko
      name: Telegram
    - icon: fontawesome/solid/envelope
      link: mailto:k.boiko2002@mail.ru
      name: Email
  generator: false

# Navigation
nav:
  - Главная: index.md
  - О себе: about.md
  - Проекты: projects.md
  - Контакты: contacts.md

# Plugins
plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html


